version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=reddit-clone
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    ports:
      - '3306:3306'
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - mysql:/var/lib/mysql
      - cache:/data
volumes:
  mysql:
    driver: local
  cache:
    driver: local

# mysql -u root -p; "secret"
# use reddit-clone;
# grant all privileges to reddit-clone.* 'admin'@'%';
# flush privileges;
