version: '3.5'

services:
  postgres:
    container_name: reddit-clone
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "3300:5432"

volumes:
  postgres-db:
    driver: local